query GetAgenda {
  getAgenda {
    _id
    title
    startDate
    endDate
    rRule
    exDate
  }
}

mutation CreateAgenda {
  createAgenda(input: { title: "xxx", startDate: "2020-02-03T00:06:15.039Z" }) {
    _id
    title
    startDate
  }
}

mutation UpdateAgendaById {
  updateAgendaById(
    input: {
      id: "fe105ed5-95f9-45bf-a063-0dab0720a932"
      title: "fuck"
      startDate: "2020-02-03T00:06:15.039Z"
    }
  ) {
    _id
    title
    startDate
  }
}

mutation DeleteAgendaById {
  deleteAgendaById(id: "f4b445d6-d569-4a29-a760-da497675db38") {
    _id
    title
  }
}
