mutation CreateAnnouncement {
  createAnnouncement(input: { content: "the first announcement" }) {
    _id
    content
    createdAt
    updatedAt
  }
}

query GetAnnouncements {
  getAnnouncements {
    _id
    content
    createdAt
    updatedAt
  }
}

mutation UpdateAnnouncementById {
  updateAnnouncementById(
    input: { id: "f4b445d6-d569-4a29-a760-da497675db38", content: "the 1st announcement." }
  ) {
    _id
    content
    createdAt
    updatedAt
  }
}

mutation DeleteAnnouncementById {
  deleteAnnouncementById(id: "f4b445d6-d569-4a29-a760-da497675db38") {
    _id
    content
    createdAt
    updatedAt
  }
}

mutation DeleteAnnouncements {
  deleteAnnouncements(
    ids: ["60e5c5a2-f69f-41df-bc04-53f9c699e498", "00c602bd-e364-491d-abb1-45cf930ac443"]
  ) {
    n
    ok
    deletedCount
  }
}
