mutation CreateLiveTour {
  createLiveTour(
    input: { title: "test4", posterUrl: "https://1test4.com", showTime: "2019-12-26T07:14:07.655Z" }
  ) {
    _id
    title
    posterUrl
    showTime
    createdAt
    updatedAt
  }
}

query GetLiveTours {
  getLiveTours {
    _id
    title
    posterUrl
    showTime
    createdAt
    updatedAt
  }
}

mutation UpdateLiveTourById {
  updateLiveTourById(
    input: {
      id: "f4b445d6-d569-4a29-a760-da497675db38"
      title: "test2"
      posterUrl: "https://1test4.com"
      showTime: "2019-12-26T07:14:07.655Z"
    }
  ) {
    _id
    title
    posterUrl
    showTime
    createdAt
    updatedAt
  }
}

mutation DeleteLiveTourById {
  deleteLiveTourById(id: "f4b445d6-d569-4a29-a760-da497675db38") {
    _id
    title
    posterUrl
    showTime
    createdAt
    updatedAt
  }
}

mutation DeleteLiveTours {
  deleteLiveTours(
    ids: ["60e5c5a2-f69f-41df-bc04-53f9c699e498", "00c602bd-e364-491d-abb1-45cf930ac443"]
  ) {
    n
    ok
    deletedCount
  }
}
