mutation CreatePlayer {
  createPlayer(
    input: {
      title: "イチリンソウ"
      artist: "山本彩"
      lrc: "歌词"
      coverUrl: "https://t4est3.com"
      musicFileUrl: "https://1test4.com"
      isPublic: true
    }
  ) {
    _id
    title
    artist
    lrc
    coverUrl
    musicFileUrl
    isPublic
    createdAt
    updatedAt
  }
}

query GetPlayer {
  getPlayer {
    _id
    title
    artist
    lrc
    coverUrl
    musicFileUrl
    isPublic
    createdAt
    updatedAt
  }
}

mutation UpdatePlayerById {
  updatePlayerById(
    input: {
      id: "f4b445d6-d569-4a29-a760-da497675db38"
      title: "夕焼けの歌"
      artist: "近藤真彦"
      lrc: "歌词"
      coverUrl: "https://t5est4.com"
      musicFileUrl: "https://2test5.com"
    }
  ) {
    _id
    title
    artist
    lrc
    coverUrl
    musicFileUrl
    isPublic
    createdAt
    updatedAt
  }
}

mutation DeletePlayerById {
  deletePlayerById(id: "f4b445d6-d569-4a29-a760-da497675db38") {
    _id
    title
    artist
    lrc
    coverUrl
    musicFileUrl
    isPublic
    createdAt
    updatedAt
  }
}

mutation DeletePlayer {
  deletePlayer(
    ids: ["60e5c5a2-f69f-41df-bc04-53f9c699e498", "00c602bd-e364-491d-abb1-45cf930ac443"]
  ) {
    n
    ok
    deletedCount
  }
}

mutation SwitchIsPubilc {
  switchIsPubilc(
    ids: ["60e5c5a2-f69f-41df-bc04-53f9c699e498", "00c602bd-e364-491d-abb1-45cf930ac443"]
  ) {
    n
    ok
    deletedCount
  }
}